openapi: "3.1.0"
info:
  title: "ufrogamelab_backend API"
  description: "ufrogamelab_backend API"
  version: "1.0.0"
servers:
  - url: "https://ufrogamelab_backend"
paths:
  /v1/account/user/profile/edit/{id}:
    put:
      summary: "PUT v1/account/user/profile/edit/{id}"
      operationId: "editProfile"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequestDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileResponseDTO"
  /v1/account/user/profile/{profileId}:
    get:
      summary: "GET v1/account/user/profile/{profileId}"
      operationId: "getProfileById"
      parameters:
        - name: "profileId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileResponseDTO"
  /v1/account/user/become-developer:
    put:
      summary: "PUT v1/account/user/become-developer"
      operationId: "convertToDeveloper"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GenericMessageResponseDTO"
  /v1/account/user/{id}:
    get:
      summary: "GET v1/account/user/{id}"
      operationId: "getUserById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserResponseDTO"
  /v1/collection/leaderboards/{gameId}:
    get:
      summary: "GET v1/collection/leaderboards/{gameId}"
      operationId: "leaderboard"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "limit"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "10"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/collection/my-games:
    get:
      summary: "GET v1/collection/my-games"
      operationId: "listMyGames"
      parameters:
        - name: "hidden"
          in: "query"
          required: false
          schema:
            type: "boolean"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/collection/my-games/{gameId}:
    get:
      summary: "GET v1/collection/my-games/{gameId}"
      operationId: "getMyGame"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/collection/my-games/{gameId}/favorite-status:
    put:
      summary: "PUT v1/collection/my-games/{gameId}/favorite-status"
      operationId: "updateFavorite"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/collection/my-games/{gameId}/hidden-status:
    put:
      summary: "PUT v1/collection/my-games/{gameId}/hidden-status"
      operationId: "updateHidden"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/collection/my-games/{gameId}/launch-info:
    get:
      summary: "GET v1/collection/my-games/{gameId}/launch-info"
      operationId: "launchInfo"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/collection/my-games/{gameId}/session-update:
    put:
      summary: "PUT v1/collection/my-games/{gameId}/session-update"
      operationId: "sessionUpdate"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/develop/estadisticasGlobalesJuego/{id}:
    get:
      summary: "GET v1/develop/estadisticasGlobalesJuego/{id}"
      operationId: "getGameStatistics"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/develop/infoJuego:
    get:
      summary: "GET v1/develop/infoJuego"
      operationId: "getAllGames"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    post:
      summary: "POST v1/develop/infoJuego"
      operationId: "publishGameInfo"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameInfoRequestDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/develop/infoJuego/{id}:
    get:
      summary: "GET v1/develop/infoJuego/{id}"
      operationId: "getGameById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    put:
      summary: "PUT v1/develop/infoJuego/{id}"
      operationId: "updateGameInfo"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameInfoRequestDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /store/games:
    get:
      summary: "GET store/games"
      operationId: "getAllGames"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/GameDTO"
  /store/games/{gameId}:
    get:
      summary: "GET store/games/{gameId}"
      operationId: "getGame"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/GameDTO"
  /store/games/{gameId}/reviews:
    get:
      summary: "GET store/games/{gameId}/reviews"
      operationId: "listReviews"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    put:
      summary: "PUT store/games/{gameId}/reviews"
      operationId: "updateReview"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    post:
      summary: "POST store/games/{gameId}/reviews"
      operationId: "addReview"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    delete:
      summary: "DELETE store/games/{gameId}/reviews"
      operationId: "deleteReview"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /store/wishlist:
    get:
      summary: "GET store/wishlist"
      operationId: "getWishlist"
      parameters:
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /store/wishlist/games:
    post:
      summary: "POST store/wishlist/games"
      operationId: "addGame"
      parameters:
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddToWishlistRequestDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /store/wishlist/games/{gameId}:
    delete:
      summary: "DELETE store/wishlist/games/{gameId}"
      operationId: "removeGame"
      parameters:
        - name: "gameId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: false
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /v1/account/auth/login:
    post:
      summary: "POST v1/account/auth/login"
      operationId: "loginUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/LoginResponseDTO"
  /v1/account/auth/register:
    post:
      summary: "POST v1/account/auth/register"
      operationId: "registerUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequestDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    UpdateProfileRequestDTO:
      type: "object"
      properties:
        name:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        avatarUrl:
          type: "string"
          nullable: true
    ProfileResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        nickname:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        avatarUrl:
          type: "string"
          nullable: true
    GenericMessageResponseDTO:
      type: "object"
      properties:
        message:
          type: "string"
          nullable: true
    UserResponseDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        name:
          type: "string"
          nullable: true
        email:
          type: "string"
          nullable: true
        isDeveloper:
          type: "boolean"
          nullable: true
    GameMetadataDTO:
      type: "object"
      properties:
        developer:
          type: "string"
          nullable: true
        genres:
          type: "array"
          nullable: true
          items:
            type: "string"
    GameMultimediaDTO:
      type: "object"
      properties:
        trailer:
          type: "string"
          nullable: true
        screenshots:
          type: "array"
          nullable: true
          items:
            type: "string"
    GameInfoRequestDTO:
      type: "object"
      properties:
        title:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        price:
          type: "number"
          format: "double"
          nullable: true
        metadata:
          nullable: true
          $ref: "#/components/schemas/GameMetadataDTO"
        multimedia:
          nullable: true
          $ref: "#/components/schemas/GameMultimediaDTO"
        shortDescription:
          type: "string"
          nullable: true
    GameDTO:
      type: "object"
      properties:
        gameId:
          type: "integer"
          format: "int64"
          nullable: true
        title:
          type: "string"
          nullable: true
        genre:
          type: "string"
          nullable: true
        price:
          type: "number"
          format: "double"
          nullable: true
    ReviewDTO:
      type: "object"
      properties:
        rating:
          type: "integer"
          format: "int32"
          nullable: true
        title:
          type: "string"
          nullable: true
        comment:
          type: "string"
          nullable: true
    AddToWishlistRequestDTO:
      type: "object"
      properties:
        gameId:
          type: "integer"
          format: "int64"
          nullable: true
    LoginRequestDTO:
      type: "object"
      properties:
        username:
          type: "string"
          nullable: true
        password:
          type: "string"
          nullable: true
    LoginResponseDTO:
      type: "object"
      properties:
        accessToken:
          type: "string"
          nullable: true
        refreshToken:
          type: "string"
          nullable: true
    RegisterRequestDTO:
      type: "object"
      properties:
        username:
          type: "string"
          nullable: true
        email:
          type: "string"
          nullable: true
        password:
          type: "string"
          nullable: true
        isDeveloper:
          type: "boolean"
          nullable: true